In [143]:
import numpy as np
import pandas as pd
from PIL import Image
import urllib
from os import listdir
from os.path import isfile, join


## Create a list of appart ID / picture urls

In [2]:
df_listing_high_renter = pd.read_csv('data/df_listing_high_renter.csv')

In [3]:
df_listing_all = pd.read_csv('data/listings.csv')

In [24]:
col_url = [col for col in df_listing_all.columns if 'url' in col]

In [29]:
df_listing_all[df_listing_all.id==4106583][col_url].transpose()

18254
listing_url                      https://www.airbnb.com/rooms/4106583
thumbnail_url       https://a0.muscache.com/im/pictures/52427497/3...
medium_url          https://a0.muscache.com/im/pictures/52427497/3...
picture_url         https://a0.muscache.com/im/pictures/52427497/3...
xl_picture_url      https://a0.muscache.com/im/pictures/52427497/3...
host_url                   https://www.airbnb.com/users/show/20998252
host_thumbnail_url  https://a0.muscache.com/im/users/20998252/prof...
host_picture_url    https://a0.muscache.com/im/users/20998252/prof...

In [32]:
df_listing_all[df_listing_all.id==4106583][col_url].xl_picture_url.values

array([ 'https://a0.muscache.com/im/pictures/52427497/3b3b7391_original.jpg?aki_policy=x_large'], dtype=object)

In [35]:
print df_listing_high_renter.shape
print df_listing_all.shape

(3199, 521)
(20576, 95)


In [41]:
df_pictures_url = pd.merge(df_listing_high_renter[['id']], df_listing_all[['id']+col_url], on='id')

In [125]:
df_pictures_url.head(9)

id                            listing_url  \
0  15767215  https://www.airbnb.com/rooms/15767215   
1   7568544   https://www.airbnb.com/rooms/7568544   
2  16926322  https://www.airbnb.com/rooms/16926322   
3  16153479  https://www.airbnb.com/rooms/16153479   
4  16865367  https://www.airbnb.com/rooms/16865367   
5   4604780   https://www.airbnb.com/rooms/4604780   
6    768616    https://www.airbnb.com/rooms/768616   
7  14542554  https://www.airbnb.com/rooms/14542554   
8   4119526   https://www.airbnb.com/rooms/4119526   

                                       thumbnail_url  \
0  https://a0.muscache.com/im/pictures/0947cd5e-a...   
1  https://a0.muscache.com/im/pictures/96046046/5...   
2  https://a0.muscache.com/im/pictures/f6591c6f-0...   
3  https://a0.muscache.com/im/pictures/95f34d39-0...   
4  https://a0.muscache.com/im/pictures/485ee9b7-b...   
5  https://a0.muscache.com/im/pictures/57819996/8...   
6  https://a0.muscache.com/im/pictures/24245246/0...   
7  https://a0.muscache.com/im/pictures/a8473a20-b...   
8  https://a0.muscache.com/im/pictures/c04a4268-a...   

                                          medium_url  \
0  https://a0.muscache.com/im/pictures/0947cd5e-a...   
1  https://a0.muscache.com/im/pictures/96046046/5...   
2  https://a0.muscache.com/im/pictures/f6591c6f-0...   
3  https://a0.muscache.com/im/pictures/95f34d39-0...   
4  https://a0.muscache.com/im/pictures/485ee9b7-b...   
5  https://a0.muscache.com/im/pictures/57819996/8...   
6  https://a0.muscache.com/im/pictures/24245246/0...   
7  https://a0.muscache.com/im/pictures/a8473a20-b...   
8  https://a0.muscache.com/im/pictures/c04a4268-a...   

                                         picture_url  \
0  https://a0.muscache.com/im/pictures/0947cd5e-a...   
1  https://a0.muscache.com/im/pictures/96046046/5...   
2  https://a0.muscache.com/im/pictures/f6591c6f-0...   
3  https://a0.muscache.com/im/pictures/95f34d39-0...   
4  https://a0.muscache.com/im/pictures/485ee9b7-b...   
5  https://a0.muscache.com/im/pictures/57819996/8...   
6  https://a0.muscache.com/im/pictures/24245246/0...   
7  https://a0.muscache.com/im/pictures/a8473a20-b...   
8  https://a0.muscache.com/im/pictures/c04a4268-a...   

                                      xl_picture_url  \
0  https://a0.muscache.com/im/pictures/0947cd5e-a...   
1  https://a0.muscache.com/im/pictures/96046046/5...   
2  https://a0.muscache.com/im/pictures/f6591c6f-0...   
3  https://a0.muscache.com/im/pictures/95f34d39-0...   
4  https://a0.muscache.com/im/pictures/485ee9b7-b...   
5  https://a0.muscache.com/im/pictures/57819996/8...   
6  https://a0.muscache.com/im/pictures/24245246/0...   
7  https://a0.muscache.com/im/pictures/a8473a20-b...   
8  https://a0.muscache.com/im/pictures/c04a4268-a...   

                                      host_url  \
0   https://www.airbnb.com/users/show/39537907   
1   https://www.airbnb.com/users/show/39056052   
2   https://www.airbnb.com/users/show/25707959   
3  https://www.airbnb.com/users/show/105373097   
4  https://www.airbnb.com/users/show/112381310   
5   https://www.airbnb.com/users/show/23822141   
6    https://www.airbnb.com/users/show/4054647   
7    https://www.airbnb.com/users/show/2227611   
8   https://www.airbnb.com/users/show/21370854   

                                  host_thumbnail_url  \
0  https://a0.muscache.com/im/pictures/3a69d1b4-7...   
1  https://a0.muscache.com/im/pictures/e710a9b1-6...   
2  https://a0.muscache.com/im/users/25707959/prof...   
3  https://a0.muscache.com/im/pictures/ea9eff09-4...   
4  https://a0.muscache.com/im/pictures/19e0e197-0...   
5  https://a0.muscache.com/im/users/23822141/prof...   
6  https://a0.muscache.com/im/users/4054647/profi...   
7  https://a0.muscache.com/im/pictures/5f018716-7...   
8  https://a0.muscache.com/im/users/21370854/prof...   

                                    host_picture_url  
0  https://a0.muscache.com/im/pictures/3a69d1b4-7...  
1  https://a0.muscache.com/im/pictures/e710a9b1-6...

In [45]:
df_pictures_url.to_csv('data/high_renters_pictures_url.csv')

## Scrap all appartment pictures for high rented flats

In [85]:
def scrap_pictures(id,url):
   
    try:
        urllib.urlretrieve(url, "data/pictures/"+  str(id )+".jpg")
    except Exception as e:
        print e
        print "cannot scrap {}".format(url)


In [135]:
def check_pictures_files_is_local(list_url):
    local_files =  [f for f in listdir('data/pictures') if isfile(join('data/pictures', f))]
    local_files =[int(f.split(".")[0]) for f in local_files]
    
    server_files = [f for f in list_url if f[0] not in local_files]
    
    
    return server_files

In [137]:
list_url = df_pictures_url[['id','picture_url']].sort_values(by='id').values.tolist()
list_url = check_pictures_files_is_local(list_url)

[]


In [138]:
#for url in list_url:
 #   scrap_pictures(url[0],url[1])

## Convert pictures to numpy array

In [268]:
size = (128, 128)

def load_image( infilename ) :
    img = Image.open( infilename).convert('RGB')
   
    
    img = img.resize(size, Image.ANTIALIAS)
    
    img.load()
    
    
    data = np.asarray(img, dtype="int32" )
    save_image(data)
    data = data.reshape(1,-1)
    return data,img

def save_image( npdata) :
    img = Image.fromarray( np.asarray( np.clip(npdata,0,255), dtype="uint8"), "RGB" )
    img.show()
    


In [269]:
data,img = load_image('data/pictures/81081.jpg')

In [274]:
print type(img.getcolors())

<type 'NoneType'>


In [285]:

import scipy
import scipy.misc
import scipy.cluster

NUM_CLUSTERS = 5

print 'reading image'
im = Image.open('data/pictures/81081.jpg')
im = im.resize((150, 150))      # optional, to reduce time
ar = scipy.misc.fromimage(im)
ar = ar.astype(float)
shape = ar.shape
ar = ar.reshape(scipy.product(shape[:2]), shape[2])

print 'finding clusters'
codes, dist = scipy.cluster.vq.kmeans(ar, NUM_CLUSTERS)
print 'cluster centres:\n', codes

vecs, dist = scipy.cluster.vq.vq(ar, codes)         # assign codes
counts, bins = scipy.histogram(vecs, len(codes))    # count occurrences

index_max = scipy.argmax(counts)                    # find most frequent
peak = codes[index_max]

print counts

peak = peak.astype(int)
colour = ''.join(chr(c) for c in peak).encode('hex')
print 'most frequent is %s (#%s)' % (peak, colour)

reading image
finding clusters
cluster centres:
[[  31.46345117   22.43618933    9.63211504]
 [ 201.30205216  181.91256947  163.63958957]
 [ 226.4619323   216.35630985  208.65241301]
 [ 159.46686747  100.23433735   22.30662651]
 [ 114.84189723   92.61089152   87.98550725]]
[ 3320  4521 10729  1658  2272]
most frequent is [226 216 208] (#e2d8d0)
